[package]
name = "gossip-support"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sp-application-crypto = { path = "../../../../substrate/primitives/application-crypto" }
sp-keystore = { path = "../../../../substrate/primitives/keystore" }
sp-core = { path = "../../../../substrate/primitives/core" }
sc-network = { path = "../../../../substrate/client/network" }
sc-network-common = { path = "../../../../substrate/client/network/common" }

node-network-protocol = { path = "../protocol" }
node-subsystem = { path = "../../subsystem" }
node-subsystem-util = { path = "../../subsystem-util" }
primitives = { path = "../../../primitives" }

futures = "0.3.21"
futures-timer = "3.0.2"
rand = { version = "0.8.5", default-features = false }
rand_chacha = { version = "0.3.1", default-features = false }
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
sp-consensus-babe = { path = "../../../../substrate/primitives/consensus/babe" }
sp-tracing = { path = "../../../../substrate/primitives/tracing" }
sp-authority-discovery = { path = "../../../../substrate/primitives/authority-discovery" }

node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }

assert_matches = "1.4.0"
async-trait = "0.1.57"
lazy_static = "1.4.0"
