[package]
name = "test-parachain-undying-collator"
description = "Collator for the undying test parachain"
edition.workspace = true
license.workspace = true
version = "1.0.0"
authors.workspace = true
publish = false

[[bin]]
name = "undying-collator"
path = "src/main.rs"

[dependencies]
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["derive"] }
clap = { version = "4.4.6", features = ["derive"] }
futures = "0.3.21"
futures-timer = "3.0.2"
log = "0.4.17"

test-parachain-undying = { path = ".." }
primitives = { path = "../../../../primitives" }
infrablockchain-cli = { path = "../../../../cli" }
infrablockchain-service = { path = "../../../../node/service", features = ["rococo-native"] }
node-primitives = { path = "../../../../node/primitives" }
node-subsystem = { path = "../../../../node/subsystem" }

sc-cli = { path = "../../../../../substrate/client/cli" }
sp-core = { path = "../../../../../substrate/primitives/core" }
sc-service = { path = "../../../../../substrate/client/service" }

[dev-dependencies]
parachain-primitives = { path = "../../.." }
polkadot-test-service = { path = "../../../../node/test/service" }
node-core-pvf = { path = "../../../../node/core/pvf", features = ["test-utils"] }

substrate-test-utils = { path = "../../../../../substrate/test-utils" }
sc-service = { path = "../../../../../substrate/client/service" }
sp-keyring = { path = "../../../../../substrate/primitives/keyring" }

tokio = { version = "1.24.2", features = ["macros"] }
