[package]
name = "node-core-pvf-checker"
description = "Polkadot crate that implements the PVF pre-checking subsystem. Responsible for checking and voting for PVFs that are pending approval."
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.21"
thiserror = "1.0.48"
gum = { package = "tracing-gum", path = "../../gum" }

node-primitives = { path = "../../primitives" }
node-subsystem = { path = "../../subsystem" }
primitives = { path = "../../../primitives" }
node-subsystem-util = { path = "../../subsystem-util" }
infrablockchain-overseer = { path = "../../overseer" }

sp-keystore = { path = "../../../../substrate/primitives/keystore" }

[dev-dependencies]
sp-core = { path = "../../../../substrate/primitives/core" }
sp-runtime = { path = "../../../../substrate/primitives/runtime" }
sc-keystore = { path = "../../../../substrate/client/keystore" }
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../../primitives/test-helpers" }
sp-application-crypto = { path = "../../../../substrate/primitives/application-crypto" }
futures-timer = "3.0.2"
